SELECT PD.ID_PEDIDO, 
	   PD.DATA_PEDIDO,
	   CL.NOME,
	   SUM(IP.PREÇO_UNITARIO * IP.QUANTIDADE)
  FROM PEDIDO PD
  INNER JOIN CLIENTE CL
  ON PD.ID_CLIENT = CL.ID_CLIENT
  INNER JOIN ITEM_PEDIDO IP
  ON PD.ID_PEDIDO = IP.ID_PEDIDO
  WHERE PD.DATA_PEDIDO >=  TO_DATE('01/01/2012', 'DD/MM/YYYY') and PD.DATA_PEDIDO <= TO_DATE('31/12/2012', 'DD/MM/YYYY')
  GROUP BY PD.ID_PEDIDO,
		   PD.DATA_PEDIDO,
		   CL.NOME
  ORDER BY PD.DATA_PEDIDO;
  
INSERT INTO PRODUTO (DESCRICAO, PRECO_UNITARIO, QUANTIDADE) VALUES ('SMART TV', 1950,00, 1);

UPDATE PRODUTO SET DESCRICAO = 'Notebook' WHERE ID_PRODUTO = 10